dist: xenial
language: node_js
node_js:
  - "10"
script: npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: target/deploy
  target-branch: deploy
  on:
    branch: master
